site_name: lian's cheatsheet

markdown_extensions:
  - toc:
      permalink: true

nav:
    - Home: index.md
    - Seafile:
      - common conf: seafile/conf.md
      - CAS: seafile/cas/cas.md
    - tools:
      - linux: tools/linux.md
      - vim: tools/vim.md
      - git: tools/git.md
      - docker: tools/docker.md
      - nginx: tools/nginx.md
      - certbot: tools/certbot.md
      - onlyoffice: tools/onlyoffice.md
      - mysql: tools/mysql.md
      - memcached: tools/memcached.md
    - About: about.md

theme: readthedocs
