site_name: lian's cheatsheet

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - django

nav:
    - Home: index.md
    - AI: AI/chatGPT.md
    - Seafile:
      - common conf: seafile/conf.md
      - CAS: seafile/cas/cas.md
      - scripts:
        - upload-file.py: seafile/scripts/upload-file.py
    - Python:
      - django: python/django.md
      - logging: python/logging.md
      - base64: python/base64.md
      - PIL: python/pil.md
      - ldap: python/ldap.md
      - restful-api: python/restful-api.md
      - elasticsearch: python/elasticsearch.md
      - notebook: python/notebook.md
      - scripts:
        - auto-toc.py: python/scripts/auto-toc.py
    - saml2:
      - saml2/saml2.md
    - Linux:
      - linux/linux.md
      - linux/shell.md
      - linux/process-and-thread.md
    - Mysql:
      - mysql/mysql.md
      - mysql/troubleshoot.md
    - Network:
      - network/http.md
    - Docker:
      - docker/docker.md
    - OnlyOffice:
      - onlyoffice/onlyoffice.md
    - CollaboraOffice:
      - collabora-office/code.md
    - MacOS:
      - macos/vimrc.md
      - macos/bash_profile.md
    - tools:
      - regex: tools/regex.md
      - vim: tools/vim.md
      - git: tools/git.md
      - tmux: tools/tmux.md
      - nginx: tools/nginx.md
      - certbot: tools/certbot.md
      - memcached: tools/memcached.md
      - science online: tools/science-online.md
      - ngrok: tools/ngrok.md
    - About: about.md
