site_name: lian's cheatsheet

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - django

nav:
    - Home: index.md
    - Seafile:
      - common conf: seafile/conf.md
      - CAS: seafile/cas/cas.md
    - Python:
      - django: python/django.md
      - logging: python/logging.md
      - PIL: python/pil.md
      - ldap: python/ldap.md
      - saml2.0: python/saml2.0.md
      - restful-api: python/restful-api.md
      - elasticsearch: python/elasticsearch.md
      - scripts:
        - auto-toc.py: python/scripts/auto-toc.py
    - Linux:
      - linux/linux.md
      - linux/shell.md
      - linux/process-and-thread.md
    - Mysql:
      - mysql/mysql.md
      - mysql/mysql-troubleshoot.md
    - Docker:
      - docker/docker.md
    - OnlyOffice:
      - onlyoffice/onlyoffice.md
    - tools:
      - regex: tools/regex.md
      - vim: tools/vim.md
      - git: tools/git.md
      - tmux: tools/tmux.md
      - nginx: tools/nginx.md
      - certbot: tools/certbot.md
      - memcached: tools/memcached.md
      - science online: tools/science-online.md
    - About: about.md
