site_name: lian's cheatsheet

nav:
    - Home: index.md
    - Python:
      - logging: python/logging.md
      - PIL: python/pil.md
    - Seafile:
      - common conf: seafile/conf.md
      - CAS: seafile/cas/cas.md
    - tools:
      - linux: tools/linux.md
      - vim: tools/vim.md
      - git: tools/git.md
      - tmux: tools/tmux.md
      - docker: tools/docker.md
      - nginx: tools/nginx.md
      - certbot: tools/certbot.md
      - onlyoffice: tools/onlyoffice.md
      - mysql: tools/mysql.md
      - memcached: tools/memcached.md
      - science online: tools/science-online.md
    - About: about.md

theme: readthedocs
